version: "3"
services:
  backoffice_backend:
    build:
      context: ./backoffice
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: "iguanas_bank_backoffice_prod"
    ports:
      - '8081:8081'
    env_file:
      - ./backoffice/env/prod/backend.env
    #environment:
    # - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://backoffice_db:5432/iguanas_bank_backoffice
    depends_on:
      - backoffice_db
      - transation_validator_backend
  transation_validator_backend:
    build:
      context: ./transation-validator
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: "iguanas_bank_transaction_validator_prod"
    ports:
      - '8082:8082'
    env_file:
      - ./transation-validator/env/prod/backend.env
    depends_on:
      - transation_validator_db                
      
  backoffice_db:
    image: "postgres:12.1"
    container_name: "db_backoffice_prod"
    ports:
      - "5432:5432"
    volumes:
      - ./backoffice/db-init/prod/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
      - v_backoffice_data:/var/lib/postgresql/data
      
  transation_validator_db:
    image: "postgres:12.1"
    container_name: "db_transaction_validator_prod"
    ports:
      - "5433:5432"
    volumes:
      - ./transation-validator/db-init/prod/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
      - v_transation_validator:/var/lib/postgresql/data      

volumes:
  v_backoffice_data:
  v_transation_validator: