
    create table tb_bank_account (
       ba_id int8 generated by default as identity,
        ba_alteration_date timestamp not null,
        ba_creation_date timestamp not null,
        ba_account_code varchar(255) not null,
        ba_account_code_vd varchar(255) not null,
        ba_active boolean not null,
        ba_agency_code varchar(255) not null,
        ba_agency_code_vd varchar(255) not null,
        us_id_customer int8 not null,
        us_id_manager int8 not null,
        bat_id int8 not null,
        primary key (ba_id)
    );

    create table tb_bank_account_type (
       bat_id int8 generated by default as identity,
        bat_alteration_date timestamp not null,
        bat_creation_date timestamp not null,
        bat_code int4 not null,
        bat_description varchar(255),
        bat_name varchar(255) not null,
        primary key (bat_id)
    );

    create table tb_bank_internal_oper (
       bio_id int8 generated by default as identity,
        bio_alteration_date timestamp not null,
        bio_creation_date timestamp not null,
        bio_operation_method int4 not null,
        bio_operation_status int4 not null,
        bio_operation_type int4 not null,
        bio_operation_value numeric(19, 2) not null,
        us_id_beneficiary int8 not null,
        us_id_owner int8 not null,
        primary key (bio_id)
    );

    create table tb_profile (
       us_id int8 not null,
        pro_name int4
    );

    create table tb_user_system (
       us_id int8 generated by default as identity,
        us_alteration_date timestamp not null,
        us_creation_date timestamp not null,
        us_birthday_date date not null,
        us_email varchar(255) not null,
        us_gender int4 not null,
        us_name varchar(255) not null,
        primary key (us_id)
    );

    alter table if exists tb_user_system
       add constraint UK_p2xjwvmg17pfbj81t9ej5lc8n unique (us_email);

    alter table if exists tb_bank_account
       add constraint FKk3tk76p6h24j2tiie1s685m46
       foreign key (us_id_customer)
       references tb_user_system;

    alter table if exists tb_bank_account
       add constraint FKgfypb5k576py8peygrqgatmyg
       foreign key (us_id_manager)
       references tb_user_system;

    alter table if exists tb_bank_account
       add constraint FKmv5vcmisomgrui0s3c8y2ur72
       foreign key (bat_id)
       references tb_bank_account_type;

    alter table if exists tb_bank_internal_oper
       add constraint FKpfxy2l6st27iye9sr2m9ditqu
       foreign key (us_id_beneficiary)
       references tb_user_system;

    alter table if exists tb_bank_internal_oper
       add constraint FKcx1ce6hi6bye7cmoa43rhfl8b
       foreign key (us_id_owner)
       references tb_user_system;

    alter table if exists tb_profile
       add constraint FKjgd7foihg4qqd8nhkr9mugxgf
       foreign key (us_id)
       references tb_user_system;