    create table tb_transaction_validator (
       tv_id int8 generated by default as identity,
        tv_alteration_date timestamp not null,
        tv_creation_date timestamp not null,
        tv_is_valid boolean not null,
        tv_key varchar(255) not null,
        tv_operation_id int8 not null,
        primary key (tv_id)
    );